- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/subscription_details.scala.html
- conf/app.routes
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
(cherry picked from commit ec61b42)
> [APB-569][ph] added mock subscription details page

- app/uk/gov/hmrc/agentsubscriptionfrontend/GuiceModule.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/auth/MtdSubscriberRegime.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/auth/NoOpRegime.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/config/frontendAppConfig.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/config/frontendGlobal.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/config/frontendWiring.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/error_template.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/govuk_wrapper.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/main_template.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/subscribe.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/subscription_details.scala.html
- conf/application.conf
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
first stab with some commented code and tests. This is deliberate so that we can parallelise development more quickly.
> [APB-488][ph] first stab at auth on check agency status

- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/subscribe.scala.html
- conf/messages
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/controllers/FieldMappingsSpec.scala
Previously no validation error message would be displayed when an invalid UTR was entered.
> [FD][APB-498] Fix UTR validation

- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/check_agency_status.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/controllers/FieldMappingsSpec.scala
Note: to avoid conflicts this branch uses #14 as a starting point which means that this PR includes #14's changes.
> [FD][APB-498] Add postcode format validation 

- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/check_agency_status.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/controllers/FieldMappingsSpec.scala
...to improve user experience if they refresh their browser after submitting a form.
> [FD][APB-498] Use Post/Redirect/Get pattern

- app/uk/gov/hmrc/agentsubscriptionfrontend/views/check_agency_status.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/start.scala.html
> Frontend and content

- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/models/Registration.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/confirm_your_agency.scala.html
- it/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentSubscriptionConnectorISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/BaseControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/stubs/AgentSubscriptionStub.scala
This adds the main logic for APB-515 but we still need to add the Not Subscribed page (see pending test and TODO).
> APB-515 Send user to Already Subscribed page if they are already subscribed

- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/models/KnownFactsResult.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/subscription_details.scala.html
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/BaseControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
It may now hold an individual name or an organisation name.
Includes commits from #34 to avoid conflicts.
> [FD][APB-668] Rename field to reflect its new purpose

- app/uk/gov/hmrc/agentsubscriptionfrontend/views/check_agency_status.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/confirm_your_agency.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/not_subscribed.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/start.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/subscription_complete.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/subscription_details.scala.html
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/StartControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
Copy refined across the service to match latest content provided by Kate Lloyd. Minor changes to some form elements.
> [BW][APB-737] - Copy refined across service

- app/uk/gov/hmrc/agentsubscriptionfrontend/views/govuk_wrapper.scala.html
Removing title from header across all pages.
> [BW] -Header title removed from insideHeader

- app/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentSubscriptionConnector.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/KnownFacts.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/package.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/models/KnownFactsResult.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/models/Subscription.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/confirm_your_agency.scala.html
- it/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentSubscriptionConnectorISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/stubs/AgentSubscriptionStub.scala
- project/FrontendBuild.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/controllers/FieldMappingsSpec.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/service/SessionStoreServiceSpec.scala
- add dependency to agent-mtd-identifiers lib
- validate using new `Utr.isValid(...)`
- switch from String to `Utr`
> [AO][APB-772] add dependency to agent-mtd-identifiers lib

- conf/messages
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
> [ZF][APB-724] Changed message displayed to user

- project/MicroService.scala
Fixed regex for coverageExcludedPackages so it will ignore routes filesetc...
> [CC][APB-1019] Fix scoverage excluded packages

- app/uk/gov/hmrc/agentsubscriptionfrontend/auth/AuthActions.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/auth/Enrolment.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/config/frontendAppConfig.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- conf/application.conf
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/support/EndpointBehaviours.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/auth/AuthActionSpec.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/config/appConfig/AsRedirectUrlSpec.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/support/TestAppConfig.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/views/ViewsSpec.scala
already subscribed: HMRC-AS-AGENT enrolment and its activated delete non async Wrapper fix tests respectively
> [APB-1045][DK,LS]rewrite AuthWrapper in order to check if Agent is

- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
* Fix name.
* Use hopefully clearer way of asserting that the subscription details page has been shown.
> [FD,TA][APB-870] Make test clearer

- app/uk/gov/hmrc/agentsubscriptionfrontend/service/SubscriptionService.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
Prior to APB-1014 if the user chose a non-UK country we ignored their choice and sent "GB" to the DES subscription API anyway.
APB-1014 changed that so now we send the country sent by the user.
This commit changes the behaviour back so we always send "GB".
This is an interim fix - when we do APB-1288 we will inform the user that non-UK addresses are not allowed instead of silently ignoring their choice of country.
> [FD][APB-1014,APB-1288] Quick fix for behaviour change introduced in APB-1014

- app/assets/javascripts/scripts.js
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/package.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/address_form_with_errors.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/check_agency_status.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/start.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/subscription_details.scala.html
- conf/messages
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/CheckAgencyControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/controllers/DesAddressFormSpec.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/controllers/FieldMappingsSpec.scala
[APB-1679]
[APB-1677]
[APB-1676]
[APB-1674]
[APB-1656]
[APB-1657]
[APB-1658]
[APB-1680]
[APB-1721]
> Accessibility fixes

- app/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentAssuranceConnector.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/stubs/AgentAssuranceStub.scala
was NotFoundException instead of Upstream4xx so changed to appropriate
> [APB-1779][AK,RV] fixed 404 error

- app/uk/gov/hmrc/agentsubscriptionfrontend/auth/AuthActions.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/config/frontendAppConfig.scala
- conf/application.conf
- conf/logback.xml
- it/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentAssuranceConnectorISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentSubscriptionConnectorISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/stubs/DataStreamStubs.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/views/ViewsSpec.scala
and tidy up tests log, and fix few connectors tests
> [APB-2047][AO] fix problem with local authentication redirect missing `localhost:port` prefix

- app/uk/gov/hmrc/agentsubscriptionfrontend/views/check_answers.scala.html
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SubscriptionControllerISpec.scala
Reverts hmrc/agent-subscription-frontend#223
> Revert "[ASA-19][RV] add back button to check-answers page"

- .gitignore
- app/uk/gov/hmrc/agentsubscriptionfrontend/auth/AuthActions.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentSubscriptionConnector.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/BusinessDetailsController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/BusinessIdentificationController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/service/SubscriptionJourneyService.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/existing_journey_found.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentSubscriptionConnectorISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/BusinessDetailsControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/BusinessIdentificationControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/stubs/AgentSubscriptionJourneyStub.scala
> [APB-4095][SM] New user entering UTR for existing record gets redirected to warning page

- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/StartController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/sign_in_check.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/start.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/StartControllerISpec.scala
Warning page just after user signs in that gives them the opportunity to sign in with their new world creds if they have them and then continue to their agent services account or create some if they don't.
> [APB-4588][MP] Add page to warn users they are signing in with old creds

- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/StartController.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/StartControllerISpec.scala
because they are setting up a new agent services account
> [APB-4588][MP] don't show clean agents the sign in warning page

- app/assets/javascripts/as-fe.js
- app/assets/javascripts/session-timeout.js
- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SignedOutController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/govuk_wrapper.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/main_template.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/timed_out.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/SignOutControllerISpec.scala
Different behaviour depending on whether user has manually signed out or pop up has timed out
> [APB-4629][MP] fix timeout

- app/uk/gov/hmrc/agentsubscriptionfrontend/controllers/BusinessIdentificationController.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/service/SubscriptionJourneyService.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/already_started.scala.html
- build.sbt
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/BusinessIdentificationControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/stubs/AgentSubscriptionJourneyStub.scala
Any idea how to test this, it's a slightly tricky scenario?
> [APB-5129][BS] returning agents error page

- conf/messages.en
The Welsh here is apparently already correct
> APB-5316 [CS] RAD content update to CYA

- app/uk/gov/hmrc/agentsubscriptionfrontend/views/amls/amls_details.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/business_type.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/client_details.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/company_registration.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/components/CheckAnswersRow.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/components/InputSelect.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/components/SubmitButton.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/components/SubmitOrSaveButtonGroup.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/components/UkAddress.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/confirm_business.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/contact_email_address.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/contact_email_check.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/contact_trading_name.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/contact_trading_name_check.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/invasive_check_start.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/registered_for_vat.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/vat_details.scala.html
- handle empty change link in CYA [accessibility fix]
- add missing classes for fieldset & input widths
- spacing after submit buttons
> APB-5526 [CS] | style fixes

- app/uk/gov/hmrc/agentsubscriptionfrontend/views/amls/amls_details.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/amls/amls_record_ineligible_status.scala.html
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/vat_details.scala.html
vrn & membership number input & link spacing with deskpro on `amls_record_ineligible_status`
> APB-5533 [CS] | style fixes

- app/uk/gov/hmrc/agentsubscriptionfrontend/validators/CommonValidators.scala
- app/uk/gov/hmrc/agentsubscriptionfrontend/views/business_email.scala.html
- conf/messages.cy
- conf/messages.en
- it/uk/gov/hmrc/agentsubscriptionfrontend/controllers/ContactDetailsControllerISpec.scala
- it/uk/gov/hmrc/agentsubscriptionfrontend/support/Css.scala
- test/uk/gov/hmrc/agentsubscriptionfrontend/validators/CommonValidatorsSpec.scala
> APB-5624 [CS] | refactor email message keys

- build.sbt
prevents issue in jenkins parsing test reports
> [CS] disable JUnitXml plugin

- conf/messages.cy
> Welsh tidy up and translation

- it/test/uk/gov/hmrc/agentsubscriptionfrontend/connectors/AgentSubscriptionConnectorISpecIt.scala
- it/test/uk/gov/hmrc/agentsubscriptionfrontend/stubs/AgentSubscriptionStub.scala
> APB-9412 created test for connector
